#!/usr/bin/env zsh
# ===================================================================
# Catppuccin Theme Generator
# ===================================================================
# Generates tool-specific config files from colors.json
# ===================================================================

set -e

SCRIPT_DIR="${0:A:h}"
COLORS_FILE="$SCRIPT_DIR/colors.json"
OUTPUT_DIR="$SCRIPT_DIR/generated"

# Source gum_utils if available
if [[ -f "$HOME/.config/shell/gum_utils.sh" ]]; then
    source "$HOME/.config/shell/gum_utils.sh"
elif [[ -f "${SCRIPT_DIR}/../shell/gum_utils.sh" ]]; then
    source "${SCRIPT_DIR}/../shell/gum_utils.sh"
else
    # Fallback functions
    gum_info() { echo "→ $*"; }
    gum_success() { echo "✓ $*"; }
    gum_error() { echo "ERROR: $*" >&2; }
fi

# Verify dependencies
if ! command -v jq >/dev/null 2>&1; then
    gum_error "jq is required but not installed"
    exit 1
fi

BC_AVAILABLE=false
if command -v bc >/dev/null 2>&1; then
    BC_AVAILABLE=true
elif [[ "$OSTYPE" == "darwin"* ]]; then
    gum_error "bc is required on macOS (for iTerm profile generation) but not installed"
    exit 1
fi

# Verify colors.json exists
if [[ ! -f "$COLORS_FILE" ]]; then
    gum_error "colors.json not found at $COLORS_FILE"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Convert hex to iTerm RGB format (0.0-1.0 floats)
hex_to_iterm_rgb() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))

    local r_float=$(printf "%.10f" $(echo "scale=10; $r / 255" | bc))
    local g_float=$(printf "%.10f" $(echo "scale=10; $g / 255" | bc))
    local b_float=$(printf "%.10f" $(echo "scale=10; $b / 255" | bc))

    echo "{\"Red Component\": $r_float, \"Green Component\": $g_float, \"Blue Component\": $b_float, \"Alpha Component\": 1, \"Color Space\": \"sRGB\"}"
}

# Strip # from hex color
strip_hash() {
    echo "${1#\#}"
}

gum_info "Generating theme files from colors.json..."

# ===================================================================
# 1. Generate shell-colors.sh
# ===================================================================
gum_info "Generating shell-colors.sh..."

cat > "$OUTPUT_DIR/shell-colors.sh" << 'HEADER'
#!/usr/bin/env zsh
# ===================================================================
# Catppuccin Mocha Shell Colors
# Auto-generated by generate-theme.sh - DO NOT EDIT
# ===================================================================

HEADER

# Export each color as CATPPUCCIN_* env var
jq -r 'to_entries[] | "export CATPPUCCIN_\(.key | ascii_upcase)=\"\(.value)\""' "$COLORS_FILE" >> "$OUTPUT_DIR/shell-colors.sh"

# Add FZF color scheme
cat >> "$OUTPUT_DIR/shell-colors.sh" << 'FZF_SECTION'

# FZF Catppuccin color scheme
export FZF_CATPPUCCIN_COLORS="--color=bg+:#313244,bg:#181825,spinner:#f5e0dc,hl:#a6e3a1 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#a6e3a1"
FZF_SECTION

gum_success "Generated shell-colors.sh"

# ===================================================================
# 2. Generate p10k-colors.zsh
# ===================================================================
gum_info "Generating p10k-colors.zsh..."

cat > "$OUTPUT_DIR/p10k-colors.zsh" << 'HEADER'
#!/usr/bin/env zsh
# ===================================================================
# Catppuccin Mocha Powerlevel10k Colors
# Auto-generated by generate-theme.sh - DO NOT EDIT
# ===================================================================

HEADER

# Export each color as P10K_COLOR_* typeset var
jq -r 'to_entries[] | "typeset -g P10K_COLOR_\(.key | ascii_upcase)=\"\(.value)\""' "$COLORS_FILE" >> "$OUTPUT_DIR/p10k-colors.zsh"

gum_success "Generated p10k-colors.zsh"

# ===================================================================
# 3. Generate tmux-colors.conf
# ===================================================================
gum_info "Generating tmux-colors.conf..."

cat > "$OUTPUT_DIR/tmux-colors.conf" << 'HEADER'
# ===================================================================
# Catppuccin Mocha Tmux Colors
# Auto-generated by generate-theme.sh - DO NOT EDIT
# ===================================================================

HEADER

# Export each color as @thm_* option
jq -r 'to_entries[] | "set -g @thm_\(.key) \"\(.value)\""' "$COLORS_FILE" >> "$OUTPUT_DIR/tmux-colors.conf"

gum_success "Generated tmux-colors.conf"

# ===================================================================
# 4. Generate iterm-profile.json (macOS only, requires bc)
# ===================================================================
base=$(jq -r '.base' "$COLORS_FILE")
text=$(jq -r '.text' "$COLORS_FILE")
surface0=$(jq -r '.surface0' "$COLORS_FILE")
surface1=$(jq -r '.surface1' "$COLORS_FILE")
surface2=$(jq -r '.surface2' "$COLORS_FILE")
overlay1=$(jq -r '.overlay1' "$COLORS_FILE")
rosewater=$(jq -r '.rosewater' "$COLORS_FILE")
red=$(jq -r '.red' "$COLORS_FILE")
green=$(jq -r '.green' "$COLORS_FILE")
yellow=$(jq -r '.yellow' "$COLORS_FILE")
blue=$(jq -r '.blue' "$COLORS_FILE")
mauve=$(jq -r '.mauve' "$COLORS_FILE")
teal=$(jq -r '.teal' "$COLORS_FILE")
subtext1=$(jq -r '.subtext1' "$COLORS_FILE")
peach=$(jq -r '.peach' "$COLORS_FILE")
pink=$(jq -r '.pink' "$COLORS_FILE")
sky=$(jq -r '.sky' "$COLORS_FILE")
lavender=$(jq -r '.lavender' "$COLORS_FILE")
flamingo=$(jq -r '.flamingo' "$COLORS_FILE")
maroon=$(jq -r '.maroon' "$COLORS_FILE")
crust=$(jq -r '.crust' "$COLORS_FILE")

if [[ "$OSTYPE" == "darwin"* ]] && [[ "$BC_AVAILABLE" == true ]]; then
    gum_info "Generating iterm-profile.json..."

    cat > "$OUTPUT_DIR/iterm-profile.json.tmp" << HEADER
{
  "Profiles": [
    {
      "Name": "Catppuccin Mocha",
      "Guid": "catppuccin-mocha-generated",
      "Dynamic Profile Parent Name": "Default",
      "Draw Powerline Glyphs": true,
      "Background Color": $(hex_to_iterm_rgb "$base"),
      "Foreground Color": $(hex_to_iterm_rgb "$text"),
      "Cursor Color": $(hex_to_iterm_rgb "$rosewater"),
      "Cursor Text Color": $(hex_to_iterm_rgb "$crust"),
      "Selection Color": $(hex_to_iterm_rgb "$surface1"),
      "Selected Text Color": $(hex_to_iterm_rgb "$text"),
      "Bold Color": $(hex_to_iterm_rgb "$text"),
      "Link Color": $(hex_to_iterm_rgb "$blue"),
      "Ansi 0 Color": $(hex_to_iterm_rgb "$surface1"),
      "Ansi 1 Color": $(hex_to_iterm_rgb "$red"),
      "Ansi 2 Color": $(hex_to_iterm_rgb "$green"),
      "Ansi 3 Color": $(hex_to_iterm_rgb "$yellow"),
      "Ansi 4 Color": $(hex_to_iterm_rgb "$blue"),
      "Ansi 5 Color": $(hex_to_iterm_rgb "$pink"),
      "Ansi 6 Color": $(hex_to_iterm_rgb "$teal"),
      "Ansi 7 Color": $(hex_to_iterm_rgb "$subtext1"),
      "Ansi 8 Color": $(hex_to_iterm_rgb "$surface1"),
      "Ansi 9 Color": $(hex_to_iterm_rgb "$red"),
      "Ansi 10 Color": $(hex_to_iterm_rgb "$green"),
      "Ansi 11 Color": $(hex_to_iterm_rgb "$yellow"),
      "Ansi 12 Color": $(hex_to_iterm_rgb "$blue"),
      "Ansi 13 Color": $(hex_to_iterm_rgb "$pink"),
      "Ansi 14 Color": $(hex_to_iterm_rgb "$teal"),
      "Ansi 15 Color": $(hex_to_iterm_rgb "$subtext1")
    }
  ]
}
HEADER
    mv "$OUTPUT_DIR/iterm-profile.json.tmp" "$OUTPUT_DIR/iterm-profile.json"

    gum_success "Generated iterm-profile.json"
else
    gum_dim "Skipped iterm-profile.json (macOS + bc required)"
fi

# ===================================================================
# 5. Generate cursor-overrides.json
# ===================================================================
gum_info "Generating cursor-overrides.json..."

mantle=$(jq -r '.mantle' "$COLORS_FILE")

cat > "$OUTPUT_DIR/cursor-overrides.json" << HEADER
{
  "workbench.colorTheme": "Catppuccin Mocha",
  "workbench.preferredDarkColorTheme": "Catppuccin Mocha",
  "window.autoDetectColorScheme": false,
  "terminal.integrated.fontFamily": "MesloLGS NF, MesloLGS Nerd Font, Menlo, monospace",
  "workbench.colorCustomizations": {
    "editor.background": "$base",
    "editor.foreground": "$text",
    "sideBar.background": "$mantle",
    "sideBar.foreground": "$text",
    "sideBarSectionHeader.background": "$base",
    "activityBar.background": "$crust",
    "activityBar.foreground": "$text",
    "terminal.background": "$base",
    "terminal.foreground": "$text",
    "titleBar.activeBackground": "$crust",
    "titleBar.activeForeground": "$text",
    "titleBar.inactiveBackground": "$mantle",
    "titleBar.inactiveForeground": "$subtext1",
    "tab.activeBackground": "$base",
    "tab.activeForeground": "$text",
    "tab.inactiveBackground": "$mantle",
    "tab.inactiveForeground": "$subtext1",
    "editorGroupHeader.tabsBackground": "$mantle",
    "panel.background": "$base",
    "panel.border": "$surface0",
    "statusBar.background": "$crust",
    "statusBar.foreground": "$text",
    "input.background": "$surface0",
    "input.foreground": "$text",
    "input.border": "$surface1",
    "dropdown.background": "$surface0",
    "dropdown.foreground": "$text",
    "list.activeSelectionBackground": "$surface0",
    "list.activeSelectionForeground": "$text",
    "list.hoverBackground": "$surface1",
    "list.focusBackground": "$surface1",
    "editorGutter.background": "$base",
    "editorLineNumber.foreground": "$surface1",
    "editorLineNumber.activeForeground": "$lavender",
    "breadcrumb.background": "$base",
    "breadcrumb.foreground": "$text",
    "breadcrumbPicker.background": "$mantle",
    "editorWidget.background": "$mantle",
    "editorWidget.border": "$surface0",
    "editorHoverWidget.background": "$mantle",
    "editorHoverWidget.border": "$surface0",
    "editorSuggestWidget.background": "$mantle",
    "editorSuggestWidget.border": "$surface0",
    "peekView.border": "$surface0",
    "peekViewEditor.background": "$base",
    "peekViewResult.background": "$mantle",
    "peekViewTitle.background": "$mantle",
    "scrollbar.shadow": "$crust",
    "scrollbarSlider.background": "$surface0",
    "scrollbarSlider.hoverBackground": "$surface1",
    "scrollbarSlider.activeBackground": "$surface2",
    "minimap.background": "$base",
    "editorGroup.border": "$surface0",
    "editorGroup.dropBackground": "$surface0",
    "editorGroupHeader.border": "$surface0",
    "tab.border": "$base",
    "tab.activeBorder": "$base",
    "tab.unfocusedActiveBorder": "$base",
    "sideBarTitle.foreground": "$text",
    "sideBarSectionHeader.foreground": "$text",
    "textLink.foreground": "$blue",
    "textLink.activeForeground": "$sky",
    "editorCursor.foreground": "$rosewater",
    "editorCursor.background": "$crust",
    "[Catppuccin Mocha]": {
      "editor.background": "$base",
      "editor.foreground": "$text",
      "sideBar.background": "$mantle",
      "sideBar.foreground": "$text",
      "sideBarSectionHeader.background": "$base",
      "activityBar.background": "$crust",
      "activityBar.foreground": "$text",
      "terminal.background": "$base",
      "terminal.foreground": "$text",
      "titleBar.activeBackground": "$crust",
      "titleBar.activeForeground": "$text",
      "titleBar.inactiveBackground": "$mantle",
      "titleBar.inactiveForeground": "$subtext1",
      "tab.activeBackground": "$base",
      "tab.activeForeground": "$text",
      "tab.inactiveBackground": "$mantle",
      "tab.inactiveForeground": "$subtext1",
      "editorGroupHeader.tabsBackground": "$mantle",
      "panel.background": "$base",
      "panel.border": "$surface0",
      "statusBar.background": "$crust",
      "statusBar.foreground": "$text",
      "input.background": "$surface0",
      "input.foreground": "$text",
      "input.border": "$surface1",
      "dropdown.background": "$surface0",
      "dropdown.foreground": "$text",
      "list.activeSelectionBackground": "$surface0",
      "list.activeSelectionForeground": "$text",
      "list.hoverBackground": "$surface1",
      "list.focusBackground": "$surface1",
      "editorGutter.background": "$base",
      "editorLineNumber.foreground": "$surface1",
      "editorLineNumber.activeForeground": "$lavender",
      "breadcrumb.background": "$base",
      "breadcrumb.foreground": "$text",
      "breadcrumbPicker.background": "$mantle",
      "editorWidget.background": "$mantle",
      "editorWidget.border": "$surface0",
      "editorHoverWidget.background": "$mantle",
      "editorHoverWidget.border": "$surface0",
      "editorSuggestWidget.background": "$mantle",
      "editorSuggestWidget.border": "$surface0",
      "peekView.border": "$surface0",
      "peekViewEditor.background": "$base",
      "peekViewResult.background": "$mantle",
      "peekViewTitle.background": "$mantle",
      "scrollbar.shadow": "$crust",
      "scrollbarSlider.background": "$surface0",
      "scrollbarSlider.hoverBackground": "$surface1",
      "scrollbarSlider.activeBackground": "$surface2",
      "minimap.background": "$base",
      "editorGroup.border": "$surface0",
      "editorGroup.dropBackground": "$surface0",
      "editorGroupHeader.border": "$surface0",
      "tab.border": "$base",
      "tab.activeBorder": "$base",
      "tab.unfocusedActiveBorder": "$base",
      "sideBarTitle.foreground": "$text",
      "sideBarSectionHeader.foreground": "$text",
      "textLink.foreground": "$blue",
      "textLink.activeForeground": "$sky",
      "editorCursor.foreground": "$rosewater",
      "editorCursor.background": "$crust"
    }
  }
}
HEADER

gum_success "Generated cursor-overrides.json"

# ===================================================================
# 6. Generate Cursor theme extension
# ===================================================================
gum_info "Generating Cursor theme extension..."

cursor_extension_dir="$OUTPUT_DIR/cursor-theme-extension"
cursor_theme_dir="$cursor_extension_dir/themes"
mkdir -p "$cursor_theme_dir"

cat > "$cursor_extension_dir/package.json" << HEADER
{
  "name": "catppuccin-mocha-generated",
  "displayName": "Catppuccin Mocha Generated",
  "description": "Generated Catppuccin Mocha theme from dotfiles/theme/colors.json.",
  "version": "0.0.1",
  "publisher": "parrot",
  "engines": {
    "vscode": "^1.80.0"
  },
  "categories": [
    "Themes"
  ],
  "contributes": {
    "themes": [
      {
        "label": "Catppuccin Mocha",
        "uiTheme": "vs-dark",
        "path": "./themes/catppuccin-mocha-color-theme.json"
      }
    ]
  }
}
HEADER

cat > "$cursor_theme_dir/catppuccin-mocha-color-theme.json" << HEADER
{
  "name": "Catppuccin Mocha",
  "type": "dark",
  "colors": {
    "editor.background": "$base",
    "editor.foreground": "$text",
    "sideBar.background": "$mantle",
    "sideBar.foreground": "$text",
    "sideBarSectionHeader.background": "$base",
    "activityBar.background": "$crust",
    "activityBar.foreground": "$text",
    "terminal.background": "$base",
    "terminal.foreground": "$text",
    "titleBar.activeBackground": "$crust",
    "titleBar.activeForeground": "$text",
    "titleBar.inactiveBackground": "$mantle",
    "titleBar.inactiveForeground": "$subtext1",
    "tab.activeBackground": "$base",
    "tab.activeForeground": "$text",
    "tab.inactiveBackground": "$mantle",
    "tab.inactiveForeground": "$subtext1",
    "editorGroupHeader.tabsBackground": "$mantle",
    "panel.background": "$base",
    "panel.border": "$surface0",
    "statusBar.background": "$crust",
    "statusBar.foreground": "$text",
    "input.background": "$surface0",
    "input.foreground": "$text",
    "input.border": "$surface1",
    "dropdown.background": "$surface0",
    "dropdown.foreground": "$text",
    "list.activeSelectionBackground": "$surface0",
    "list.activeSelectionForeground": "$text",
    "list.hoverBackground": "$surface1",
    "list.focusBackground": "$surface1",
    "editorGutter.background": "$base",
    "editorLineNumber.foreground": "$surface1",
    "editorLineNumber.activeForeground": "$lavender",
    "breadcrumb.background": "$base",
    "breadcrumb.foreground": "$text",
    "breadcrumbPicker.background": "$mantle",
    "editorWidget.background": "$mantle",
    "editorWidget.border": "$surface0",
    "editorHoverWidget.background": "$mantle",
    "editorHoverWidget.border": "$surface0",
    "editorSuggestWidget.background": "$mantle",
    "editorSuggestWidget.border": "$surface0",
    "peekView.border": "$surface0",
    "peekViewEditor.background": "$base",
    "peekViewResult.background": "$mantle",
    "peekViewTitle.background": "$mantle",
    "scrollbar.shadow": "$crust",
    "scrollbarSlider.background": "$surface0",
    "scrollbarSlider.hoverBackground": "$surface1",
    "scrollbarSlider.activeBackground": "$surface2",
    "minimap.background": "$base",
    "editorGroup.border": "$surface0",
    "editorGroup.dropBackground": "$surface0",
    "editorGroupHeader.border": "$surface0",
    "tab.border": "$base",
    "tab.activeBorder": "$base",
    "tab.unfocusedActiveBorder": "$base",
    "sideBarTitle.foreground": "$text",
    "sideBarSectionHeader.foreground": "$text",
    "textLink.foreground": "$blue",
    "textLink.activeForeground": "$sky",
    "editorCursor.foreground": "$rosewater",
    "editorCursor.background": "$crust"
  },
  "tokenColors": [
    {
      "scope": ["comment", "punctuation.definition.comment"],
      "settings": { "foreground": "$overlay1", "fontStyle": "italic" }
    },
    {
      "scope": ["string", "constant.other.symbol"],
      "settings": { "foreground": "$green" }
    },
    {
      "scope": ["constant.numeric", "constant.language", "support.constant"],
      "settings": { "foreground": "$peach" }
    },
    {
      "scope": ["keyword", "storage.type", "storage.modifier"],
      "settings": { "foreground": "$mauve" }
    },
    {
      "scope": ["entity.name.function", "support.function"],
      "settings": { "foreground": "$blue" }
    },
    {
      "scope": ["variable", "meta.definition.variable.name"],
      "settings": { "foreground": "$text" }
    },
    {
      "scope": ["entity.name.type", "support.type", "entity.name.class"],
      "settings": { "foreground": "$yellow" }
    },
    {
      "scope": ["entity.name.tag", "support.class.component"],
      "settings": { "foreground": "$red" }
    },
    {
      "scope": ["entity.other.attribute-name", "support.type.property-name"],
      "settings": { "foreground": "$teal" }
    }
  ],
  "semanticTokenColors": {
    "variable.readonly": "$peach",
    "property": "$teal",
    "function": "$blue",
    "method": "$blue",
    "class": "$yellow",
    "interface": "$yellow",
    "enum": "$yellow",
    "keyword": "$mauve",
    "comment": "$overlay1"
  }
}
HEADER

gum_success "Generated Cursor theme extension"

# ===================================================================
# 7. Generate Codex app theme
# ===================================================================
gum_info "Generating codex-app-theme.toml..."

codex_theme_file="$OUTPUT_DIR/codex-app-theme.toml"
codex_config_file="$SCRIPT_DIR/../codex/config.toml"

cat > "$codex_theme_file" << HEADER
[desktop.appearanceLightChromeTheme]
accent = "$peach"
contrast = 60
ink = "$text"
opaqueWindows = false
surface = "$base"

[desktop.appearanceLightChromeTheme.fonts]

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "$green"
diffRemoved = "$red"
skill = "$mauve"

[desktop.appearanceDarkChromeTheme]
accent = "$peach"
contrast = 60
ink = "$text"
opaqueWindows = false
surface = "$base"

[desktop.appearanceDarkChromeTheme.fonts]

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "$green"
diffRemoved = "$red"
skill = "$mauve"
HEADER

upsert_desktop_setting() {
    local config_file="$1"
    local key="$2"
    local value="$3"
    local tmp_file="${config_file}.tmp"
    local file_mode
    file_mode=$(stat -f '%Lp' "$config_file")

    if rg -q "^${key}[[:space:]]*=" "$config_file"; then
        awk -v key="$key" -v value="$value" '
            $0 ~ "^" key "[[:space:]]*=" { $0 = key " = " value }
            { print }
        ' "$config_file" > "$tmp_file"
        chmod "$file_mode" "$tmp_file"
        mv "$tmp_file" "$config_file"
        return 0
    fi

    if rg -q '^\[desktop\]$' "$config_file"; then
        awk -v key="$key" -v value="$value" '
            /^\[desktop\]$/ { print; print key " = " value; next }
            { print }
        ' "$config_file" > "$tmp_file"
        chmod "$file_mode" "$tmp_file"
        mv "$tmp_file" "$config_file"
        return 0
    fi

    {
        cat "$config_file"
        printf '\n[desktop]\n%s = %s\n' "$key" "$value"
    } > "$tmp_file"
    chmod "$file_mode" "$tmp_file"
    mv "$tmp_file" "$config_file"
}

upsert_codex_chrome_theme() {
    local config_file="$1"
    local theme_file="$2"
    local tmp_file="${config_file}.tmp"
    local file_mode
    file_mode=$(stat -f '%Lp' "$config_file")

    awk '
        /^darkCodeThemeId[[:space:]]*=/ { next }
        /^lightCodeThemeId[[:space:]]*=/ { next }
        /^\[desktop\.appearanceDarkChromeTheme([.\]]|$)/ { skip = 1; next }
        /^\[desktop\.appearanceLightChromeTheme([.\]]|$)/ { skip = 1; next }
        /^\[desktop\.darkChromeTheme([.\]]|$)/ { skip = 1; next }
        /^\[desktop\.lightChromeTheme([.\]]|$)/ { skip = 1; next }
        skip && /^\[/ { skip = 0 }
        !skip { print }
    ' "$config_file" > "$tmp_file"

    {
        # $(<file) strips trailing newlines, preventing blank lines from
        # accumulating across repeated runs
        printf '%s\n\n' "$(<"$tmp_file")"
        cat "$theme_file"
    } > "$config_file"

    chmod "$file_mode" "$config_file"
    rm -f "$tmp_file"
}

if [[ -f "$codex_config_file" ]]; then
    upsert_desktop_setting "$codex_config_file" "theme" '"dark"'
    upsert_desktop_setting "$codex_config_file" "appearanceLightCodeThemeId" '"catppuccin"'
    upsert_desktop_setting "$codex_config_file" "appearanceDarkCodeThemeId" '"catppuccin"'
    upsert_codex_chrome_theme "$codex_config_file" "$codex_theme_file"
    gum_success "Updated codex/config.toml"
else
    gum_dim "Skipped codex/config.toml update (file not found)"
fi

gum_success "Generated codex-app-theme.toml"

# ===================================================================
# 8. Generate Cursor agent (Glass) theme
# ===================================================================
# The Cursor agent/chat window ("Glass") is themed separately from the
# editor. It reads a custom theme from app storage under the key
# glass.theme.customThemesV1 and selects it via glass.theme.settingsId.
# Here we emit the full customThemesV1 wrapper object; merge_cursor_colors
# installs it into Cursor's storage.
gum_info "Generating cursor-glass-theme.json..."

glass_theme_id="catppuccin-mocha-generated"

jq --arg id "$glass_theme_id" '
  . as $c |
  {
    _v: 1,
    themes: {
      ($id): {
        name: "Catppuccin Mocha",
        source: "user",
        definition: {
          name: "Catppuccin Mocha",
          appearance: "dark",
          highContrast: false,
          sidebar: $c.base,
          chrome: $c.crust,
          editor: $c.base,
          base: $c.text,
          accent: $c.blue,
          actionLabel: $c.crust,
          brand: $c.peach,
          focus: $c.lavender,
          success: $c.green,
          warn: $c.yellow,
          danger: $c.red,
          added: $c.green,
          modified: $c.yellow,
          removed: $c.red,
          untracked: $c.teal,
          terminalAnsiBlack: $c.surface1,
          terminalAnsiRed: $c.red,
          terminalAnsiYellow: $c.yellow,
          terminalAnsiGreen: $c.green,
          terminalAnsiCyan: $c.teal,
          terminalAnsiBlue: $c.blue,
          terminalAnsiMagenta: $c.pink,
          terminalAnsiWhite: $c.subtext1,
          terminalAnsiBrightBlack: $c.surface2,
          terminalAnsiBrightRed: $c.red,
          terminalAnsiBrightYellow: $c.yellow,
          terminalAnsiBrightGreen: $c.green,
          terminalAnsiBrightCyan: $c.teal,
          terminalAnsiBrightBlue: $c.blue,
          terminalAnsiBrightMagenta: $c.pink,
          terminalAnsiBrightWhite: $c.subtext0,
          red: $c.red,
          orange: $c.peach,
          yellow: $c.yellow,
          green: $c.green,
          cyan: $c.teal,
          blue: $c.blue,
          magenta: $c.pink,
          purple: $c.mauve,
          diffAddedLineBackground: ($c.green + "33"),
          diffAddedTextBackground: ($c.green + "22"),
          diffRemovedLineBackground: ($c.red + "33"),
          diffRemovedTextBackground: ($c.red + "22")
        }
      }
    }
  }
' "$COLORS_FILE" > "$OUTPUT_DIR/cursor-glass-theme.json"

gum_success "Generated cursor-glass-theme.json"

# ===================================================================
# 9. Generate Slack theme string
# ===================================================================
# Slack custom themes are a comma-separated string of 10 hex colors,
# pasted into Preferences → Themes → "Create a custom theme".
# Slot order: Column BG, Menu BG Hover, Active Item, Active Item Text,
# Hover Item, Text Color, Active Presence, Mention Badge,
# Top Nav BG, Top Nav Text
gum_info "Generating slack-theme.txt..."

printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' \
    "$base" "$surface0" "$peach" "$crust" "$surface0" \
    "$text" "$green" "$red" "$crust" "$text" \
    > "$OUTPUT_DIR/slack-theme.txt"

gum_success "Generated slack-theme.txt"

# ===================================================================
# Summary
# ===================================================================
echo ""
gum_success "All theme files generated in $OUTPUT_DIR/"
